version: '2'
services:
      web:
        build: .
        ports:
         - "5000:5000"
         # -"5000"      will publish the internal port on a rendom port on host
        volumes:
         - .:/code
        depends_on:
         - redis
      redis:
        image: redis